import type { RacingData } from "./types";

// Deterministic demo dataset. Built lazily via makeSeed() — never at module scope.
export function makeSeed(): RacingData {
  const teams: RacingData["teams"] = [
    {
      id: "t-dune",
      name: "Dune Sovereigns",
      coach: "Halima Barouk",
      strategy: "Long-haul pacing with late surge",
      homeBase: "Merzouga",
      founded: 2011,
      colors: "Sand & Gold",
      points: 412,
      victories: 19,
    },
    {
      id: "t-anvil",
      name: "Anvil Brotherhood",
      coach: "Borin Kalstone",
      strategy: "Explosive starts, brute traction",
      homeBase: "Ironhollow",
      founded: 2008,
      colors: "Ember & Iron",
      points: 387,
      victories: 17,
    },
    {
      id: "t-mirage",
      name: "Mirage Runners",
      coach: "Yusra Adeel",
      strategy: "Heat adaptation and hydration cycling",
      homeBase: "Siwa",
      founded: 2016,
      colors: "Copper & Cream",
      points: 268,
      victories: 9,
    },
    {
      id: "t-grit",
      name: "Grit & Granite",
      coach: "Dagna Emberfell",
      strategy: "Technical terrain specialists",
      homeBase: "Stonereach",
      founded: 2019,
      colors: "Slate & Amber",
      points: 201,
      victories: 6,
    },
  ];

  const c = (
    id: string,
    name: string,
    nickname: string,
    type: RacingData["competitors"][number]["type"],
    status: RacingData["competitors"][number]["status"],
    country: string,
    age: number,
    weightKg: number,
    topSpeedKph: number,
    stamina: number,
    teamId: string | null,
    races: number,
    victories: number,
    podiums: number,
    points: number,
    bio: string,
    joinedAt: string,
  ) => ({
    id,
    name,
    nickname,
    type,
    status,
    country,
    age,
    weightKg,
    topSpeedKph,
    stamina,
    teamId,
    races,
    victories,
    podiums,
    points,
    bio,
    joinedAt,
  });

  const competitors: RacingData["competitors"] = [
    c(
      "cm-001",
      "Zahra al-Rimal",
      "The Sandstorm",
      "Camel",
      "Active",
      "Morocco",
      9,
      612,
      64,
      94,
      "t-dune",
      42,
      14,
      27,
      186,
      "Undisputed queen of the long course, famous for a closing kick that has broken three track records.",
      "2019-03-12",
    ),
    c(
      "cm-002",
      "Najm the Tall",
      "Pillar",
      "Camel",
      "Active",
      "Oman",
      7,
      648,
      61,
      88,
      "t-dune",
      35,
      9,
      19,
      141,
      "Towering stride length makes him near unbeatable on flat open desert stages.",
      "2020-06-02",
    ),
    c(
      "dw-001",
      "Borin Kalstone",
      "The Anvil",
      "Dwarf",
      "Active",
      "Ironhollow",
      54,
      98,
      38,
      97,
      "t-anvil",
      58,
      16,
      33,
      212,
      "Player-coach. Explosive over the first 400 metres and physically impossible to pass in a narrow canyon.",
      "2014-01-20",
    ),
    c(
      "dw-002",
      "Dagna Emberfell",
      "Emberfoot",
      "Dwarf",
      "Active",
      "Stonereach",
      47,
      91,
      40,
      92,
      "t-grit",
      44,
      11,
      24,
      164,
      "Technical terrain specialist with the best scree-descent split in the circuit.",
      "2016-09-08",
    ),
    c(
      "cm-003",
      "Layla Ghubar",
      "Dust Veil",
      "Camel",
      "Injured",
      "Egypt",
      6,
      575,
      66,
      81,
      "t-mirage",
      21,
      5,
      11,
      88,
      "Recovering from a tendon strain sustained at the Siwa Crossing. Expected back next season.",
      "2021-11-15",
    ),
    c(
      "dw-003",
      "Thrain Coppervein",
      "Copper",
      "Dwarf",
      "Active",
      "Ironhollow",
      39,
      104,
      36,
      90,
      "t-anvil",
      37,
      7,
      16,
      119,
      "Relentless metronome pacing; never posts a fast lap, never posts a slow one either.",
      "2018-04-30",
    ),
    c(
      "md-001",
      "Ptolemy Vance",
      "The Middleman",
      "Medium",
      "Active",
      "Malta",
      31,
      143,
      44,
      86,
      "t-mirage",
      29,
      6,
      13,
      102,
      "Competes in the medium division where camel tactics and dwarf grit collide.",
      "2020-02-11",
    ),
    c(
      "md-002",
      "Sabine Orta",
      "Halfway",
      "Medium",
      "Active",
      "Spain",
      28,
      137,
      46,
      83,
      "t-grit",
      24,
      4,
      10,
      81,
      "Rising medium-division talent with an aggressive overtaking instinct.",
      "2022-05-19",
    ),
    c(
      "cm-004",
      "Rashid ibn Sahra",
      "Nightmarch",
      "Camel",
      "Suspended",
      "UAE",
      8,
      630,
      63,
      89,
      null,
      33,
      8,
      17,
      127,
      "Suspended two events for an unsanctioned hydration supplement. Appeal pending.",
      "2017-08-25",
    ),
    c(
      "dw-004",
      "Old Grumm",
      "Grumm",
      "Dwarf",
      "Retired",
      "Stonereach",
      66,
      112,
      31,
      74,
      null,
      91,
      22,
      45,
      298,
      "Circuit legend, now a commentator. Still holds the Ironhollow Gauntlet record.",
      "2005-01-01",
    ),
    c(
      "ot-001",
      "Vesper Quill",
      "The Wildcard",
      "Other",
      "Active",
      "Unaffiliated",
      33,
      61,
      52,
      79,
      null,
      12,
      2,
      5,
      44,
      "Entered under the open classification. Nobody is entirely sure what Vesper is.",
      "2023-07-04",
    ),
    c(
      "cm-005",
      "Amina Souk",
      "Souk Special",
      "Camel",
      "Active",
      "Tunisia",
      5,
      560,
      65,
      84,
      "t-dune",
      14,
      3,
      7,
      59,
      "Youngest camel on the senior circuit; blistering on short sprint courses.",
      "2024-01-22",
    ),
    c(
      "dw-005",
      "Hilda Stonebrace",
      "Brace",
      "Dwarf",
      "Active",
      "Ironhollow",
      42,
      95,
      37,
      93,
      "t-anvil",
      31,
      6,
      15,
      108,
      "Team anchor in mixed relays, renowned for flawless handovers.",
      "2019-10-05",
    ),
    c(
      "md-003",
      "Otto Reibach",
      "Bellows",
      "Medium",
      "Injured",
      "Austria",
      35,
      149,
      42,
      80,
      "t-mirage",
      27,
      3,
      9,
      73,
      "Shoulder rehab after a collision at the Copper Canyon Dash.",
      "2019-06-17",
    ),
  ];

  const races: RacingData["races"] = [
    {
      id: "r-001",
      name: "Merzouga Grand Crossing",
      status: "Open for Registration",
      type: "Individual",
      venue: "Erg Chebbi Dunes",
      scheduledAt: "2026-10-04T07:00:00.000Z",
      distanceKm: 42,
      laps: 1,
      terrain: "Open dune field",
      surface: "Soft sand",
      elevationM: 310,
      maxParticipants: 24,
      prizePool: 85000,
      description:
        "The circuit's flagship endurance crossing. One continuous run over shifting dunes with two hydration gates.",
    },
    {
      id: "r-002",
      name: "Ironhollow Gauntlet",
      status: "Closed for Registration",
      type: "Team",
      venue: "Ironhollow Deep Track",
      scheduledAt: "2026-09-27T09:30:00.000Z",
      distanceKm: 12,
      laps: 6,
      terrain: "Underground tunnel circuit",
      surface: "Packed stone",
      elevationM: 140,
      maxParticipants: 16,
      prizePool: 60000,
      description:
        "Tight tunnel laps where traction and shoulder work matter more than raw speed. Teams of four.",
    },
    {
      id: "r-003",
      name: "Siwa Twilight Sprint",
      status: "In Progress",
      type: "Mixed",
      venue: "Siwa Oasis Flats",
      scheduledAt: "2026-09-14T16:00:00.000Z",
      distanceKm: 6,
      laps: 3,
      terrain: "Salt flats",
      surface: "Hard crust",
      elevationM: 20,
      maxParticipants: 18,
      prizePool: 32000,
      description: "Short-format evening sprint pairing one camel and one dwarf per entry.",
    },
    {
      id: "r-004",
      name: "Copper Canyon Dash",
      status: "Completed",
      type: "Individual",
      venue: "Copper Canyon",
      scheduledAt: "2026-08-16T08:00:00.000Z",
      distanceKm: 18,
      laps: 2,
      terrain: "Narrow canyon with scree descents",
      surface: "Mixed gravel",
      elevationM: 520,
      maxParticipants: 20,
      prizePool: 48000,
      description: "Technical descents and blind corners. Historically the season's most chaotic event.",
    },
    {
      id: "r-005",
      name: "Stonereach Winter Invitational",
      status: "Draft",
      type: "Team",
      venue: "Stonereach Highlands",
      scheduledAt: "2026-12-06T10:00:00.000Z",
      distanceKm: 24,
      laps: 3,
      terrain: "Frozen highland trail",
      surface: "Ice and grit",
      elevationM: 640,
      maxParticipants: 12,
      prizePool: 70000,
      description: "Invitational closing event. Course specification still under review by the committee.",
    },
    {
      id: "r-006",
      name: "Oasis Relay Classic",
      status: "Cancelled",
      type: "Mixed",
      venue: "Al-Wahat Loop",
      scheduledAt: "2026-07-19T06:30:00.000Z",
      distanceKm: 30,
      laps: 5,
      terrain: "Palm grove loop",
      surface: "Packed earth",
      elevationM: 60,
      maxParticipants: 20,
      prizePool: 25000,
      description: "Cancelled following an extreme heat advisory from the regional stewards.",
    },
  ];

  const registrations: RacingData["registrations"] = [
    {
      id: "reg-001",
      raceId: "r-001",
      competitorId: "cm-001",
      status: "Approved",
      submittedAt: "2026-09-01T10:12:00.000Z",
      note: "Defending champion entry.",
    },
    {
      id: "reg-002",
      raceId: "r-001",
      competitorId: "dw-001",
      status: "Approved",
      submittedAt: "2026-09-01T11:40:00.000Z",
      note: "Cross-division challenge entry.",
    },
    {
      id: "reg-003",
      raceId: "r-001",
      competitorId: "cm-005",
      status: "Pending",
      submittedAt: "2026-09-08T08:05:00.000Z",
      note: "First senior endurance start; requesting inside gate.",
    },
    {
      id: "reg-004",
      raceId: "r-001",
      competitorId: "ot-001",
      status: "Pending",
      submittedAt: "2026-09-09T15:22:00.000Z",
      note: "Open classification entry, awaiting eligibility review.",
    },
    {
      id: "reg-005",
      raceId: "r-001",
      competitorId: "cm-004",
      status: "Rejected",
      submittedAt: "2026-09-02T09:00:00.000Z",
      note: "Entry filed during suspension window.",
      decisionReason: "Competitor currently suspended pending appeal.",
    },
    {
      id: "reg-006",
      raceId: "r-002",
      competitorId: "dw-003",
      status: "Approved",
      submittedAt: "2026-08-20T12:00:00.000Z",
      note: "Anvil Brotherhood squad slot 2.",
    },
    {
      id: "reg-007",
      raceId: "r-002",
      competitorId: "dw-005",
      status: "Approved",
      submittedAt: "2026-08-20T12:04:00.000Z",
      note: "Anvil Brotherhood squad slot 3.",
    },
    {
      id: "reg-008",
      raceId: "r-002",
      competitorId: "dw-002",
      status: "Pending",
      submittedAt: "2026-09-10T17:45:00.000Z",
      note: "Late cross-team addition requested by Grit & Granite.",
    },
    {
      id: "reg-009",
      raceId: "r-003",
      competitorId: "cm-002",
      status: "Approved",
      submittedAt: "2026-09-03T09:15:00.000Z",
      note: "Mixed pairing with Hilda Stonebrace.",
    },
    {
      id: "reg-010",
      raceId: "r-003",
      competitorId: "dw-005",
      status: "Approved",
      submittedAt: "2026-09-03T09:16:00.000Z",
      note: "Mixed pairing with Najm the Tall.",
    },
    {
      id: "reg-011",
      raceId: "r-003",
      competitorId: "md-001",
      status: "Approved",
      submittedAt: "2026-09-04T10:02:00.000Z",
      note: "Medium division wildcard slot.",
    },
    {
      id: "reg-012",
      raceId: "r-005",
      competitorId: "md-002",
      status: "Pending",
      submittedAt: "2026-09-11T13:30:00.000Z",
      note: "Provisional invitational interest.",
    },
  ];

  const results: RacingData["results"] = [
    { id: "res-001", raceId: "r-004", competitorId: "dw-002", position: 1, timeSeconds: 2714, points: 25 },
    { id: "res-002", raceId: "r-004", competitorId: "dw-001", position: 2, timeSeconds: 2748, points: 18 },
    { id: "res-003", raceId: "r-004", competitorId: "cm-001", position: 3, timeSeconds: 2769, points: 15 },
    { id: "res-004", raceId: "r-004", competitorId: "md-001", position: 4, timeSeconds: 2822, points: 12 },
    { id: "res-005", raceId: "r-004", competitorId: "md-003", position: 5, timeSeconds: 2981, points: 10 },
  ];

  const audit: RacingData["audit"] = [
    {
      id: "aud-001",
      at: "2026-09-12T08:14:00.000Z",
      actor: "Race Organizer",
      action: "Race started",
      target: "Siwa Twilight Sprint",
      detail: "Status moved from Closed for Registration to In Progress.",
    },
    {
      id: "aud-002",
      at: "2026-09-11T13:31:00.000Z",
      actor: "Viewer",
      action: "Registration submitted",
      target: "Sabine Orta → Stonereach Winter Invitational",
      detail: "Provisional invitational interest logged.",
    },
    {
      id: "aud-003",
      at: "2026-09-10T17:46:00.000Z",
      actor: "Race Organizer",
      action: "Registration submitted",
      target: "Dagna Emberfell → Ironhollow Gauntlet",
      detail: "Late cross-team addition awaiting review.",
    },
    {
      id: "aud-004",
      at: "2026-09-05T09:20:00.000Z",
      actor: "Administrator",
      action: "Competitor suspended",
      target: "Rashid ibn Sahra",
      detail: "Two-event suspension issued for an unsanctioned supplement.",
    },
    {
      id: "aud-005",
      at: "2026-08-16T12:05:00.000Z",
      actor: "Race Organizer",
      action: "Results recorded",
      target: "Copper Canyon Dash",
      detail: "Five finishing positions recorded and points awarded.",
    },
    {
      id: "aud-006",
      at: "2026-07-18T18:40:00.000Z",
      actor: "Administrator",
      action: "Race cancelled",
      target: "Oasis Relay Classic",
      detail: "Extreme heat advisory issued by regional stewards.",
    },
  ];

  return { competitors, teams, races, registrations, results, audit };
}
